name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Setup PDM
        id: pdm_setup
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: pdm install

      - name: Read pyproject.toml with yq
        id: project_version
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -oy '.project.version' pyproject.toml

      - name: Read pyproject.toml with yq
        id: project_author
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -oy '.project.authors.0.name' pyproject.toml

      - name: Read pyproject.toml with yq
        id: project_name
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -oy '.project.name' pyproject.toml

      - name: Create docs
        run: |
          mkdir docs
          pdm run sphinx-apidoc --full \
            --ext-githubpages \
            --ext-viewcode \
            --ext-ifconfig \
            --ext-todo \
            --ext-autodoc \
            --ext-intersphinx \
            -H ${{ steps.project_name.outputs.result }} \
            -A ${{ steps.project_author.outputs.result }} \
            -V ${{ steps.project_version.outputs.result }} \
            -o docs src/*/

      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: ${{ steps.pdm_setup.outputs.python-version }}
          checkout: false
